name: Continous Integration

on:
  - "push"

jobs:
  type-coverage-report:
    name: Type coverage report
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "7.4"
          coverage: "pcov"

      - name: Installing dependencies
        run: composer install

      - name: "Run vimeo/psalm"
        run: "vendor/bin/psalm --no-progress --shepherd --show-info=false --stats"

  phpunit-integration:
    name: PHPUnit - Integration
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.4]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Installing dependencies
        run: composer install

      - name: Running integration tests
        env:
          BK_TEST_TOKEN: ${{ secrets.BK_TEST_TOKEN }}
          BK_TEST_ORG: ${{ secrets.BK_TEST_ORG }}
        run: vendor/bin/phpunit --testsuite integration

