name: Continous Integration

on:
  - "push"

jobs:
  type-coverage-report:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP with extensions"
        uses: "shivammathur/setup-php@v1"
        with:
          php-version: "7.4"
          coverage: "pcov"

      - name: "Installing dependencies"
        run: "composer install"

      - name: "Run ecs"
        run: "vendor/bin/ecs check src tests"

      - name: "Run psalm"
        run: "vendor/bin/psalm --no-progress --shepherd --show-info=false --stats"

      - name: "Generate unit test coverage report"
        run: "vendor/bin/phpunit --testsuite unit --coverage-clover php-unit-coverage.xml"

      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          file: ./php-unit-coverage.xml # optional
          flags: phpunit,unit # optional
          fail_ci_if_error: true # optional (default = false)

  phpunit:
    name: "PHPUnit"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: [7.2, 7.4]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Installing dependencies"
        run: "composer install"

      - name: "Running unit tests"
        run: "vendor/bin/phpunit --testsuite unit"
