name: Continous Integration

on: [push]

jobs:
  build:
    name: Continous Integration
    # This job runs on Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        php: [7.2, 7.4]
    steps:
      - uses: actions/checkout@v2
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: PHPUnit
        run: |
          composer install
          vendor/bin/phpunit --testsuite unit
