name: Continous Integration

on: [push]

jobs:
  build:
    name: Continous Integration
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: PHPUnit
        run: |
          docker run --rm composer:1.10 composer install
          docker run --rm php:7.2.30-alpine vendor/bin/phpunit
